name: skyward_ui_kit
description: A collection of common Skyward UI elements
version: 0.1.0
repository: https://github.com/liquidise/skyward_ui_kit

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:

# dev_dependencies:
